### ISSUE TITLE
Update code to angular 4.0

### ISSUE THREAD

**Issue by kwalrath** [Janamou/firebase-counter-steps#6]
This codelab is probably broken, due to Stagehand template changes we made when angular moved from 3.x to 4.0.

We need to do the same kinds of updates that we did to the [Write a Material Design AngularDart Web App](https://github.com/dart-lang/io_2017_components_codelab) codelab. (Here's [its code](https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app/).)

**Comment by Janamou** [comment]
@kwalrath done here: https://github.com/Janamou/firebase-counter-steps/pull/7
