### ISSUE TITLE
It's possible to set a non-integer counter value in the shared database, breaking all future codelab users

### ISSUE THREAD

**Issue by jwmcglynn** [Janamou/firebase-counter-steps#9]
The codelab uses a shared firebase database, but doesn't sufficiently validate input, so it's possible to set a decimal value that the client doesn't expect, resulting in a runtime error.

To reproduce, modify a function to set the counter to a decimal value:

```
Future<Null> like() async {
  await ref.set(60.0613);
}
```

Then, once that function is executed the AppComponent errors out with the following on load:

> (anonymous function)	(anonymous function)	fc	bf	cf	g.Jb	g.set	(anonymous function)	> EXCEPTION: type 'double' is not a subtype of type 'int' of 'value' where
>   double is from dart:core
>   int is from dart:core
> 
> STACKTRACE: 
> package:firebase_counter/app_component.dart 21:7                                        AppComponent.count=
> package:firebase_counter/app_component.dart 35:7                                        AppComponent.ngOnInit.<fn>
> dart:async                                                                              _ZoneDelegate.runUnary
> *...snip...*

To fix, either update the firebase rules or change count from a num to an int.  According to [this stackoverflow](https://stackoverflow.com/questions/44572284/how-to-validate-that-value-is-an-integer-with-firebase-rules), explicitly checking for int isn't possible, but doing a modulus to check for a whole number is sufficient to implicitly cast to an int, even when sending a value like '1.0'.  The rule would look like so:

```
{
  "rules": {
    "counter": {
      ".read": true,
      ".write": true,
      ".validate": "newData.isNumber() && newData.val() % 1 === 0.0"
    }
  }
}
```

**Comment by Janamou** [comment]
@jwmcglynn thank you! I updated the rules with the modulus :-)

**Comment by kwalrath** [comment]
@Janamou Do I need to do anything for the codelab text?

**Comment by Janamou** [comment]
@kwalrath No, we don't talk about database rules (this is out of scope of this codelab :-))
